name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f .config/requirements.txt ]; then pip install -r .config/requirements.txt; fi

      - name: Run tests (if any)
        run: |
          if ls tests/*.py 1> /dev/null 2>&1; then
            pytest -q
          else
            echo "No tests yet — skipping."
          fi
